select * from customer limit 20
Q1. What is the total revenue generated by male vs. female customers?
select gender, SUM(purchase_amount) as revenue from customer group by gender
Q2. Which customers used a discount but still spent more than the average purchase amount?
select customer_id, purchase_amount from customer where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)
Q3. Which are the top 5 products with the highest average review rating?
select item_purchased, AVG(review_rating) as "'Average Product Rating'" from customer group by item_purchased order by AVG(review_rating) desc limit 5;
Q4. Compare average Purchase Amounts between Standard and Express Shipping.
select shipping_type, ROUND(AVG(purchase_amount),2) from customer where shipping_type in ('Standard','Express') group by shipping_type;
Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status,
       COUNT(customer_id) AS total_customers,
       ROUND(AVG(purchase_amount), 2) AS average_spend,
       ROUND(SUM(purchase_amount), 2) AS total_revenue
FROM customer
GROUP BY subscription_status;

Q6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
       ROUND( (SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END) * 100.0)
              / COUNT(*)
            , 2) AS discount_rate
FROM customer
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;
Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
  SELECT
    customer_id,
    previous_purchases,
    CASE
      WHEN previous_purchases = 1 THEN 'NEW'
      WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
      ELSE 'Loyal'
    END AS customer_segment
  FROM customer
)
SELECT
  customer_segment,
  COUNT(*) AS number_of_customers
FROM customer_type
GROUP BY customer_segment;
Q8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
  SELECT
    category,
    item_purchased,
    COUNT(customer_id) AS total_orders
  FROM customer
  GROUP BY category, item_purchased
),
ranked AS (
  SELECT
    category,
    item_purchased,
    total_orders,
    ROW_NUMBER() OVER (
      PARTITION BY category
      ORDER BY total_orders DESC
    ) AS item_rank
  FROM item_counts
)
SELECT item_rank, category, item_purchased, total_orders
FROM ranked
WHERE item_rank <= 3
ORDER BY category, item_rank;

Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status,
       COUNT(customer_id) AS repeat_buyer
FROM customer
WHERE previous_purchases > 5
GROUP BY subscription_status;
Q10. What is the revenue contribution of each age group?
SELECT age_group,
       SUM(purchase_amount) AS total_revenue
FROM customer
GROUP BY age_group
ORDER BY total_revenue DESC;